services:
  # redis
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --requirepass "admin3edc*IK<"
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
